//go:build linux && cgo && !agent

package cluster

// The code below was generated by lxd-generate - DO NOT EDIT!

import (
	"context"
	"database/sql"
	"fmt"
	"net/http"

	"github.com/lxc/lxd/lxd/db/query"
	"github.com/lxc/lxd/shared/api"
)

var _ = api.ServerEnvironment{}

var imageObjects = RegisterStmt(`
SELECT images.id, projects.name AS project, images.fingerprint, images.type, images.filename, images.size, images.public, images.architecture, images.creation_date, images.expiry_date, images.upload_date, images.cached, images.last_use_date, images.auto_update
  FROM images JOIN projects ON images.project_id = projects.id
  ORDER BY projects.id, images.fingerprint
`)

var imageObjectsByID = RegisterStmt(`
SELECT images.id, projects.name AS project, images.fingerprint, images.type, images.filename, images.size, images.public, images.architecture, images.creation_date, images.expiry_date, images.upload_date, images.cached, images.last_use_date, images.auto_update
  FROM images JOIN projects ON images.project_id = projects.id
  WHERE images.id = ? ORDER BY projects.id, images.fingerprint
`)

var imageObjectsByProject = RegisterStmt(`
SELECT images.id, projects.name AS project, images.fingerprint, images.type, images.filename, images.size, images.public, images.architecture, images.creation_date, images.expiry_date, images.upload_date, images.cached, images.last_use_date, images.auto_update
  FROM images JOIN projects ON images.project_id = projects.id
  WHERE project = ? ORDER BY projects.id, images.fingerprint
`)

var imageObjectsByProjectAndCached = RegisterStmt(`
SELECT images.id, projects.name AS project, images.fingerprint, images.type, images.filename, images.size, images.public, images.architecture, images.creation_date, images.expiry_date, images.upload_date, images.cached, images.last_use_date, images.auto_update
  FROM images JOIN projects ON images.project_id = projects.id
  WHERE project = ? AND images.cached = ? ORDER BY projects.id, images.fingerprint
`)

var imageObjectsByProjectAndPublic = RegisterStmt(`
SELECT images.id, projects.name AS project, images.fingerprint, images.type, images.filename, images.size, images.public, images.architecture, images.creation_date, images.expiry_date, images.upload_date, images.cached, images.last_use_date, images.auto_update
  FROM images JOIN projects ON images.project_id = projects.id
  WHERE project = ? AND images.public = ? ORDER BY projects.id, images.fingerprint
`)

var imageObjectsByFingerprint = RegisterStmt(`
SELECT images.id, projects.name AS project, images.fingerprint, images.type, images.filename, images.size, images.public, images.architecture, images.creation_date, images.expiry_date, images.upload_date, images.cached, images.last_use_date, images.auto_update
  FROM images JOIN projects ON images.project_id = projects.id
  WHERE images.fingerprint = ? ORDER BY projects.id, images.fingerprint
`)

var imageObjectsByCached = RegisterStmt(`
SELECT images.id, projects.name AS project, images.fingerprint, images.type, images.filename, images.size, images.public, images.architecture, images.creation_date, images.expiry_date, images.upload_date, images.cached, images.last_use_date, images.auto_update
  FROM images JOIN projects ON images.project_id = projects.id
  WHERE images.cached = ? ORDER BY projects.id, images.fingerprint
`)

var imageObjectsByAutoUpdate = RegisterStmt(`
SELECT images.id, projects.name AS project, images.fingerprint, images.type, images.filename, images.size, images.public, images.architecture, images.creation_date, images.expiry_date, images.upload_date, images.cached, images.last_use_date, images.auto_update
  FROM images JOIN projects ON images.project_id = projects.id
  WHERE images.auto_update = ? ORDER BY projects.id, images.fingerprint
`)

// GetImages returns all available images.
// generator: image GetMany
func GetImages(ctx context.Context, tx *sql.Tx, filters ...ImageFilter) ([]Image, error) {
	var err error

	// Result slice.
	objects := make([]Image, 0)

	// Pick the prepared statement and arguments to use based on active criteria.
	var sqlStmt *sql.Stmt
	var args []any

	if len(filters) == 0 {
		sqlStmt = Stmt(tx, imageObjects)
		args = []any{}
	}

	if len(filters) > 0 {
		filter := filters[0]
		if filter.Project != nil && filter.Public != nil && filter.ID == nil && filter.Fingerprint == nil && filter.Cached == nil && filter.AutoUpdate == nil {
			numFilters := NumFilters(imageObjectsByProjectAndPublic)
			if len(filters) > numFilters {
				return nil, fmt.Errorf("No image statement exists for more than %d filters, found %d", len(filters), numFilters)
			}

			sqlStmt = Stmt(tx, imageObjectsByProjectAndPublic)
			projects := make([]any, numFilters)
			publics := make([]any, numFilters)
			for i, filter := range filters {
				if !(filter.Project != nil && filter.Public != nil && filter.ID == nil && filter.Fingerprint == nil && filter.Cached == nil && filter.AutoUpdate == nil) {
					return nil, fmt.Errorf("All image filters are not the same")
				}

				projects[i] = filter.Project
				publics[i] = filter.Public
			}

			args = []any{projects, publics}
		} else if filter.Project != nil && filter.Cached != nil && filter.ID == nil && filter.Fingerprint == nil && filter.Public == nil && filter.AutoUpdate == nil {
			numFilters := NumFilters(imageObjectsByProjectAndCached)
			if len(filters) > numFilters {
				return nil, fmt.Errorf("No image statement exists for more than %d filters, found %d", len(filters), numFilters)
			}

			sqlStmt = Stmt(tx, imageObjectsByProjectAndCached)
			projects := make([]any, numFilters)
			cacheds := make([]any, numFilters)
			for i, filter := range filters {
				if !(filter.Project != nil && filter.Cached != nil && filter.ID == nil && filter.Fingerprint == nil && filter.Public == nil && filter.AutoUpdate == nil) {
					return nil, fmt.Errorf("All image filters are not the same")
				}

				projects[i] = filter.Project
				cacheds[i] = filter.Cached
			}

			args = []any{projects, cacheds}
		} else if filter.Project != nil && filter.ID == nil && filter.Fingerprint == nil && filter.Public == nil && filter.Cached == nil && filter.AutoUpdate == nil {
			numFilters := NumFilters(imageObjectsByProject)
			if len(filters) > numFilters {
				return nil, fmt.Errorf("No image statement exists for more than %d filters, found %d", len(filters), numFilters)
			}

			sqlStmt = Stmt(tx, imageObjectsByProject)
			projects := make([]any, numFilters)
			for i, filter := range filters {
				if !(filter.Project != nil && filter.ID == nil && filter.Fingerprint == nil && filter.Public == nil && filter.Cached == nil && filter.AutoUpdate == nil) {
					return nil, fmt.Errorf("All image filters are not the same")
				}

				projects[i] = filter.Project
			}

			args = []any{projects}
		} else if filter.ID != nil && filter.Project == nil && filter.Fingerprint == nil && filter.Public == nil && filter.Cached == nil && filter.AutoUpdate == nil {
			numFilters := NumFilters(imageObjectsByID)
			if len(filters) > numFilters {
				return nil, fmt.Errorf("No image statement exists for more than %d filters, found %d", len(filters), numFilters)
			}

			sqlStmt = Stmt(tx, imageObjectsByID)
			ids := make([]any, numFilters)
			for i, filter := range filters {
				if !(filter.ID != nil && filter.Project == nil && filter.Fingerprint == nil && filter.Public == nil && filter.Cached == nil && filter.AutoUpdate == nil) {
					return nil, fmt.Errorf("All image filters are not the same")
				}

				ids[i] = filter.ID
			}

			args = []any{ids}
		} else if filter.Fingerprint != nil && filter.ID == nil && filter.Project == nil && filter.Public == nil && filter.Cached == nil && filter.AutoUpdate == nil {
			numFilters := NumFilters(imageObjectsByFingerprint)
			if len(filters) > numFilters {
				return nil, fmt.Errorf("No image statement exists for more than %d filters, found %d", len(filters), numFilters)
			}

			sqlStmt = Stmt(tx, imageObjectsByFingerprint)
			fingerprints := make([]any, numFilters)
			for i, filter := range filters {
				if !(filter.Fingerprint != nil && filter.ID == nil && filter.Project == nil && filter.Public == nil && filter.Cached == nil && filter.AutoUpdate == nil) {
					return nil, fmt.Errorf("All image filters are not the same")
				}

				fingerprints[i] = filter.Fingerprint
			}

			args = []any{fingerprints}
		} else if filter.Cached != nil && filter.ID == nil && filter.Project == nil && filter.Fingerprint == nil && filter.Public == nil && filter.AutoUpdate == nil {
			numFilters := NumFilters(imageObjectsByCached)
			if len(filters) > numFilters {
				return nil, fmt.Errorf("No image statement exists for more than %d filters, found %d", len(filters), numFilters)
			}

			sqlStmt = Stmt(tx, imageObjectsByCached)
			cacheds := make([]any, numFilters)
			for i, filter := range filters {
				if !(filter.Cached != nil && filter.ID == nil && filter.Project == nil && filter.Fingerprint == nil && filter.Public == nil && filter.AutoUpdate == nil) {
					return nil, fmt.Errorf("All image filters are not the same")
				}

				cacheds[i] = filter.Cached
			}

			args = []any{cacheds}
		} else if filter.AutoUpdate != nil && filter.ID == nil && filter.Project == nil && filter.Fingerprint == nil && filter.Public == nil && filter.Cached == nil {
			numFilters := NumFilters(imageObjectsByAutoUpdate)
			if len(filters) > numFilters {
				return nil, fmt.Errorf("No image statement exists for more than %d filters, found %d", len(filters), numFilters)
			}

			sqlStmt = Stmt(tx, imageObjectsByAutoUpdate)
			autoUpdates := make([]any, numFilters)
			for i, filter := range filters {
				if !(filter.AutoUpdate != nil && filter.ID == nil && filter.Project == nil && filter.Fingerprint == nil && filter.Public == nil && filter.Cached == nil) {
					return nil, fmt.Errorf("All image filters are not the same")
				}

				autoUpdates[i] = filter.AutoUpdate
			}

			args = []any{autoUpdates}
		} else if filter.ID == nil && filter.Project == nil && filter.Fingerprint == nil && filter.Public == nil && filter.Cached == nil && filter.AutoUpdate == nil {
			sqlStmt = Stmt(tx, imageObjects)
			args = []any{}
		} else {
			return nil, fmt.Errorf("No statement exists for the given Filter")
		}
	}

	// Dest function for scanning a row.
	dest := func(i int) []any {
		objects = append(objects, Image{})
		return []any{
			&objects[i].ID,
			&objects[i].Project,
			&objects[i].Fingerprint,
			&objects[i].Type,
			&objects[i].Filename,
			&objects[i].Size,
			&objects[i].Public,
			&objects[i].Architecture,
			&objects[i].CreationDate,
			&objects[i].ExpiryDate,
			&objects[i].UploadDate,
			&objects[i].Cached,
			&objects[i].LastUseDate,
			&objects[i].AutoUpdate,
		}
	}

	// Select.
	allArgs := []any{}
	for _, arg := range args {
		allArgs = append(allArgs, arg.([]any)...)
	}

	err = query.SelectObjects(sqlStmt, dest, allArgs...)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"images\" table: %w", err)
	}

	return objects, nil
}

// GetImage returns the image with the given key.
// generator: image GetOne
func GetImage(ctx context.Context, tx *sql.Tx, project string, fingerprint string) (*Image, error) {
	filter := ImageFilter{}
	filter.Project = &project
	filter.Fingerprint = &fingerprint

	objects, err := GetImages(ctx, tx, filter)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"images\" table: %w", err)
	}

	switch len(objects) {
	case 0:
		return nil, api.StatusErrorf(http.StatusNotFound, "Image not found")
	case 1:
		return &objects[0], nil
	default:
		return nil, fmt.Errorf("More than one \"images\" entry matches")
	}
}
