//go:build linux && cgo && !agent

package cluster

// The code below was generated by lxd-generate - DO NOT EDIT!

import (
	"context"
	"database/sql"
	"fmt"
	"net/http"
	"strings"

	"github.com/lxc/lxd/lxd/db/query"
	"github.com/lxc/lxd/shared/api"
)

var _ = api.ServerEnvironment{}

var instanceObjects = RegisterStmt(`
SELECT instances.id, projects.name AS project, instances.name, nodes.name AS node, instances.type, instances.architecture, instances.ephemeral, instances.creation_date, instances.stateful, instances.last_use_date, coalesce(instances.description, ''), instances.expiry_date
  FROM instances JOIN projects ON instances.project_id = projects.id JOIN nodes ON instances.node_id = nodes.id
  ORDER BY projects.id, instances.name
`)

var instanceObjectsByID = RegisterStmt(`
SELECT instances.id, projects.name AS project, instances.name, nodes.name AS node, instances.type, instances.architecture, instances.ephemeral, instances.creation_date, instances.stateful, instances.last_use_date, coalesce(instances.description, ''), instances.expiry_date
  FROM instances JOIN projects ON instances.project_id = projects.id JOIN nodes ON instances.node_id = nodes.id
  WHERE instances.id = ? ORDER BY projects.id, instances.name
`)

var instanceObjectsByProject = RegisterStmt(`
SELECT instances.id, projects.name AS project, instances.name, nodes.name AS node, instances.type, instances.architecture, instances.ephemeral, instances.creation_date, instances.stateful, instances.last_use_date, coalesce(instances.description, ''), instances.expiry_date
  FROM instances JOIN projects ON instances.project_id = projects.id JOIN nodes ON instances.node_id = nodes.id
  WHERE project = ? ORDER BY projects.id, instances.name
`)

var instanceObjectsByProjectAndType = RegisterStmt(`
SELECT instances.id, projects.name AS project, instances.name, nodes.name AS node, instances.type, instances.architecture, instances.ephemeral, instances.creation_date, instances.stateful, instances.last_use_date, coalesce(instances.description, ''), instances.expiry_date
  FROM instances JOIN projects ON instances.project_id = projects.id JOIN nodes ON instances.node_id = nodes.id
  WHERE project = ? AND instances.type = ? ORDER BY projects.id, instances.name
`)

var instanceObjectsByProjectAndTypeAndNode = RegisterStmt(`
SELECT instances.id, projects.name AS project, instances.name, nodes.name AS node, instances.type, instances.architecture, instances.ephemeral, instances.creation_date, instances.stateful, instances.last_use_date, coalesce(instances.description, ''), instances.expiry_date
  FROM instances JOIN projects ON instances.project_id = projects.id JOIN nodes ON instances.node_id = nodes.id
  WHERE project = ? AND instances.type = ? AND node = ? ORDER BY projects.id, instances.name
`)

var instanceObjectsByProjectAndTypeAndNodeAndName = RegisterStmt(`
SELECT instances.id, projects.name AS project, instances.name, nodes.name AS node, instances.type, instances.architecture, instances.ephemeral, instances.creation_date, instances.stateful, instances.last_use_date, coalesce(instances.description, ''), instances.expiry_date
  FROM instances JOIN projects ON instances.project_id = projects.id JOIN nodes ON instances.node_id = nodes.id
  WHERE project = ? AND instances.type = ? AND node = ? AND instances.name = ? ORDER BY projects.id, instances.name
`)

var instanceObjectsByProjectAndTypeAndName = RegisterStmt(`
SELECT instances.id, projects.name AS project, instances.name, nodes.name AS node, instances.type, instances.architecture, instances.ephemeral, instances.creation_date, instances.stateful, instances.last_use_date, coalesce(instances.description, ''), instances.expiry_date
  FROM instances JOIN projects ON instances.project_id = projects.id JOIN nodes ON instances.node_id = nodes.id
  WHERE project = ? AND instances.type = ? AND instances.name = ? ORDER BY projects.id, instances.name
`)

var instanceObjectsByProjectAndName = RegisterStmt(`
SELECT instances.id, projects.name AS project, instances.name, nodes.name AS node, instances.type, instances.architecture, instances.ephemeral, instances.creation_date, instances.stateful, instances.last_use_date, coalesce(instances.description, ''), instances.expiry_date
  FROM instances JOIN projects ON instances.project_id = projects.id JOIN nodes ON instances.node_id = nodes.id
  WHERE project = ? AND instances.name = ? ORDER BY projects.id, instances.name
`)

var instanceObjectsByProjectAndNameAndNode = RegisterStmt(`
SELECT instances.id, projects.name AS project, instances.name, nodes.name AS node, instances.type, instances.architecture, instances.ephemeral, instances.creation_date, instances.stateful, instances.last_use_date, coalesce(instances.description, ''), instances.expiry_date
  FROM instances JOIN projects ON instances.project_id = projects.id JOIN nodes ON instances.node_id = nodes.id
  WHERE project = ? AND instances.name = ? AND node = ? ORDER BY projects.id, instances.name
`)

var instanceObjectsByProjectAndNode = RegisterStmt(`
SELECT instances.id, projects.name AS project, instances.name, nodes.name AS node, instances.type, instances.architecture, instances.ephemeral, instances.creation_date, instances.stateful, instances.last_use_date, coalesce(instances.description, ''), instances.expiry_date
  FROM instances JOIN projects ON instances.project_id = projects.id JOIN nodes ON instances.node_id = nodes.id
  WHERE project = ? AND node = ? ORDER BY projects.id, instances.name
`)

var instanceObjectsByType = RegisterStmt(`
SELECT instances.id, projects.name AS project, instances.name, nodes.name AS node, instances.type, instances.architecture, instances.ephemeral, instances.creation_date, instances.stateful, instances.last_use_date, coalesce(instances.description, ''), instances.expiry_date
  FROM instances JOIN projects ON instances.project_id = projects.id JOIN nodes ON instances.node_id = nodes.id
  WHERE instances.type = ? ORDER BY projects.id, instances.name
`)

var instanceObjectsByTypeAndName = RegisterStmt(`
SELECT instances.id, projects.name AS project, instances.name, nodes.name AS node, instances.type, instances.architecture, instances.ephemeral, instances.creation_date, instances.stateful, instances.last_use_date, coalesce(instances.description, ''), instances.expiry_date
  FROM instances JOIN projects ON instances.project_id = projects.id JOIN nodes ON instances.node_id = nodes.id
  WHERE instances.type = ? AND instances.name = ? ORDER BY projects.id, instances.name
`)

var instanceObjectsByTypeAndNameAndNode = RegisterStmt(`
SELECT instances.id, projects.name AS project, instances.name, nodes.name AS node, instances.type, instances.architecture, instances.ephemeral, instances.creation_date, instances.stateful, instances.last_use_date, coalesce(instances.description, ''), instances.expiry_date
  FROM instances JOIN projects ON instances.project_id = projects.id JOIN nodes ON instances.node_id = nodes.id
  WHERE instances.type = ? AND instances.name = ? AND node = ? ORDER BY projects.id, instances.name
`)

var instanceObjectsByTypeAndNode = RegisterStmt(`
SELECT instances.id, projects.name AS project, instances.name, nodes.name AS node, instances.type, instances.architecture, instances.ephemeral, instances.creation_date, instances.stateful, instances.last_use_date, coalesce(instances.description, ''), instances.expiry_date
  FROM instances JOIN projects ON instances.project_id = projects.id JOIN nodes ON instances.node_id = nodes.id
  WHERE instances.type = ? AND node = ? ORDER BY projects.id, instances.name
`)

var instanceObjectsByNode = RegisterStmt(`
SELECT instances.id, projects.name AS project, instances.name, nodes.name AS node, instances.type, instances.architecture, instances.ephemeral, instances.creation_date, instances.stateful, instances.last_use_date, coalesce(instances.description, ''), instances.expiry_date
  FROM instances JOIN projects ON instances.project_id = projects.id JOIN nodes ON instances.node_id = nodes.id
  WHERE node = ? ORDER BY projects.id, instances.name
`)

var instanceObjectsByNodeAndName = RegisterStmt(`
SELECT instances.id, projects.name AS project, instances.name, nodes.name AS node, instances.type, instances.architecture, instances.ephemeral, instances.creation_date, instances.stateful, instances.last_use_date, coalesce(instances.description, ''), instances.expiry_date
  FROM instances JOIN projects ON instances.project_id = projects.id JOIN nodes ON instances.node_id = nodes.id
  WHERE node = ? AND instances.name = ? ORDER BY projects.id, instances.name
`)

var instanceObjectsByName = RegisterStmt(`
SELECT instances.id, projects.name AS project, instances.name, nodes.name AS node, instances.type, instances.architecture, instances.ephemeral, instances.creation_date, instances.stateful, instances.last_use_date, coalesce(instances.description, ''), instances.expiry_date
  FROM instances JOIN projects ON instances.project_id = projects.id JOIN nodes ON instances.node_id = nodes.id
  WHERE instances.name IN ({num_filters}) ORDER BY projects.id, instances.name
`, 200)

var instanceID = RegisterStmt(`
SELECT instances.id FROM instances JOIN projects ON instances.project_id = projects.id
  WHERE projects.name = ? AND instances.name = ?
`)

var instanceCreate = RegisterStmt(`
INSERT INTO instances (project_id, name, node_id, type, architecture, ephemeral, creation_date, stateful, last_use_date, description, expiry_date)
  VALUES ((SELECT projects.id FROM projects WHERE projects.name = ?), ?, (SELECT nodes.id FROM nodes WHERE nodes.name = ?), ?, ?, ?, ?, ?, ?, ?, ?)
`)

var instanceRename = RegisterStmt(`
UPDATE instances SET name = ? WHERE project_id = (SELECT projects.id FROM projects WHERE projects.name = ?) AND name = ?
`)

var instanceDeleteByProjectAndName = RegisterStmt(`
DELETE FROM instances WHERE project_id = (SELECT projects.id FROM projects WHERE projects.name = ?) AND name = ?
`)

var instanceUpdate = RegisterStmt(`
UPDATE instances
  SET project_id = (SELECT id FROM projects WHERE name = ?), name = ?, node_id = (SELECT id FROM nodes WHERE name = ?), type = ?, architecture = ?, ephemeral = ?, creation_date = ?, stateful = ?, last_use_date = ?, description = ?, expiry_date = ?
 WHERE id = ?
`)

// GetInstances returns all available instances.
// generator: instance GetMany
func GetInstances(ctx context.Context, tx *sql.Tx, filters ...InstanceFilter) ([]Instance, error) {
	var err error

	// Result slice.
	objects := make([]Instance, 0)

	// Pick the prepared statement and arguments to use based on active criteria.
	var sqlStmt *sql.Stmt
	var args []any

	if len(filters) == 0 {
		sqlStmt = Stmt(tx, instanceObjects)
		args = []any{}
	}

	var ids []any
	var projects []any
	var names []any
	var nodes []any
	var types []any

	for _, filter := range filters {
		if filter.ID != nil {
			if ids == nil {
				ids = []any{}
			}

			ids = append(ids, filter.ID)
		}

		if filter.Project != nil {
			if projects == nil {
				projects = []any{}
			}

			projects = append(projects, filter.Project)
		}

		if filter.Name != nil {
			if names == nil {
				names = []any{}
			}

			names = append(names, filter.Name)
		}

		if filter.Node != nil {
			if nodes == nil {
				nodes = []any{}
			}

			nodes = append(nodes, filter.Node)
		}

		if filter.Type != nil {
			if types == nil {
				types = []any{}
			}

			types = append(types, filter.Type)
		}

	}

	if len(filters) > 0 {
		if projects != nil && types != nil && nodes != nil && names != nil && ids == nil {
			if len(filters) > 1 {
				var queryStr string
				query := stmts[instanceObjectsByProjectAndTypeAndNodeAndName]
				queryStr = strings.Replace(query.query, "project = ?", fmt.Sprintf("project IN (?%s)", strings.Repeat(", ?", len(projects)-1)), -1)
				queryStr = strings.Replace(query.query, "type = ?", fmt.Sprintf("type IN (?%s)", strings.Repeat(", ?", len(types)-1)), -1)
				queryStr = strings.Replace(query.query, "node = ?", fmt.Sprintf("node IN (?%s)", strings.Repeat(", ?", len(nodes)-1)), -1)
				queryStr = strings.Replace(query.query, "name = ?", fmt.Sprintf("name IN (?%s)", strings.Repeat(", ?", len(names)-1)), -1)

				sqlStmt, err = prepare(tx, queryStr)
				if err != nil {
					return nil, fmt.Errorf("Failed to prepare stmt: %w", err)
				}
			} else {
				sqlStmt = Stmt(tx, instanceObjectsByProjectAndTypeAndNodeAndName)
			}

			args = []any{projects, types, nodes, names}
		} else if projects != nil && types != nil && nodes != nil && ids == nil && names == nil {
			if len(filters) > 1 {
				var queryStr string
				query := stmts[instanceObjectsByProjectAndTypeAndNode]
				queryStr = strings.Replace(query.query, "project = ?", fmt.Sprintf("project IN (?%s)", strings.Repeat(", ?", len(projects)-1)), -1)
				queryStr = strings.Replace(query.query, "type = ?", fmt.Sprintf("type IN (?%s)", strings.Repeat(", ?", len(types)-1)), -1)
				queryStr = strings.Replace(query.query, "node = ?", fmt.Sprintf("node IN (?%s)", strings.Repeat(", ?", len(nodes)-1)), -1)

				sqlStmt, err = prepare(tx, queryStr)
				if err != nil {
					return nil, fmt.Errorf("Failed to prepare stmt: %w", err)
				}
			} else {
				sqlStmt = Stmt(tx, instanceObjectsByProjectAndTypeAndNode)
			}

			args = []any{projects, types, nodes}
		} else if projects != nil && types != nil && names != nil && ids == nil && nodes == nil {
			if len(filters) > 1 {
				var queryStr string
				query := stmts[instanceObjectsByProjectAndTypeAndName]
				queryStr = strings.Replace(query.query, "project = ?", fmt.Sprintf("project IN (?%s)", strings.Repeat(", ?", len(projects)-1)), -1)
				queryStr = strings.Replace(query.query, "type = ?", fmt.Sprintf("type IN (?%s)", strings.Repeat(", ?", len(types)-1)), -1)
				queryStr = strings.Replace(query.query, "name = ?", fmt.Sprintf("name IN (?%s)", strings.Repeat(", ?", len(names)-1)), -1)

				sqlStmt, err = prepare(tx, queryStr)
				if err != nil {
					return nil, fmt.Errorf("Failed to prepare stmt: %w", err)
				}
			} else {
				sqlStmt = Stmt(tx, instanceObjectsByProjectAndTypeAndName)
			}

			args = []any{projects, types, names}
		} else if types != nil && names != nil && nodes != nil && ids == nil && projects == nil {
			if len(filters) > 1 {
				var queryStr string
				query := stmts[instanceObjectsByTypeAndNameAndNode]
				queryStr = strings.Replace(query.query, "type = ?", fmt.Sprintf("type IN (?%s)", strings.Repeat(", ?", len(types)-1)), -1)
				queryStr = strings.Replace(query.query, "name = ?", fmt.Sprintf("name IN (?%s)", strings.Repeat(", ?", len(names)-1)), -1)
				queryStr = strings.Replace(query.query, "node = ?", fmt.Sprintf("node IN (?%s)", strings.Repeat(", ?", len(nodes)-1)), -1)

				sqlStmt, err = prepare(tx, queryStr)
				if err != nil {
					return nil, fmt.Errorf("Failed to prepare stmt: %w", err)
				}
			} else {
				sqlStmt = Stmt(tx, instanceObjectsByTypeAndNameAndNode)
			}

			args = []any{types, names, nodes}
		} else if projects != nil && names != nil && nodes != nil && ids == nil && types == nil {
			if len(filters) > 1 {
				var queryStr string
				query := stmts[instanceObjectsByProjectAndNameAndNode]
				queryStr = strings.Replace(query.query, "project = ?", fmt.Sprintf("project IN (?%s)", strings.Repeat(", ?", len(projects)-1)), -1)
				queryStr = strings.Replace(query.query, "name = ?", fmt.Sprintf("name IN (?%s)", strings.Repeat(", ?", len(names)-1)), -1)
				queryStr = strings.Replace(query.query, "node = ?", fmt.Sprintf("node IN (?%s)", strings.Repeat(", ?", len(nodes)-1)), -1)

				sqlStmt, err = prepare(tx, queryStr)
				if err != nil {
					return nil, fmt.Errorf("Failed to prepare stmt: %w", err)
				}
			} else {
				sqlStmt = Stmt(tx, instanceObjectsByProjectAndNameAndNode)
			}

			args = []any{projects, names, nodes}
		} else if projects != nil && types != nil && ids == nil && names == nil && nodes == nil {
			if len(filters) > 1 {
				var queryStr string
				query := stmts[instanceObjectsByProjectAndType]
				queryStr = strings.Replace(query.query, "project = ?", fmt.Sprintf("project IN (?%s)", strings.Repeat(", ?", len(projects)-1)), -1)
				queryStr = strings.Replace(query.query, "type = ?", fmt.Sprintf("type IN (?%s)", strings.Repeat(", ?", len(types)-1)), -1)

				sqlStmt, err = prepare(tx, queryStr)
				if err != nil {
					return nil, fmt.Errorf("Failed to prepare stmt: %w", err)
				}
			} else {
				sqlStmt = Stmt(tx, instanceObjectsByProjectAndType)
			}

			args = []any{projects, types}
		} else if types != nil && nodes != nil && ids == nil && projects == nil && names == nil {
			if len(filters) > 1 {
				var queryStr string
				query := stmts[instanceObjectsByTypeAndNode]
				queryStr = strings.Replace(query.query, "type = ?", fmt.Sprintf("type IN (?%s)", strings.Repeat(", ?", len(types)-1)), -1)
				queryStr = strings.Replace(query.query, "node = ?", fmt.Sprintf("node IN (?%s)", strings.Repeat(", ?", len(nodes)-1)), -1)

				sqlStmt, err = prepare(tx, queryStr)
				if err != nil {
					return nil, fmt.Errorf("Failed to prepare stmt: %w", err)
				}
			} else {
				sqlStmt = Stmt(tx, instanceObjectsByTypeAndNode)
			}

			args = []any{types, nodes}
		} else if types != nil && names != nil && ids == nil && projects == nil && nodes == nil {
			if len(filters) > 1 {
				var queryStr string
				query := stmts[instanceObjectsByTypeAndName]
				queryStr = strings.Replace(query.query, "type = ?", fmt.Sprintf("type IN (?%s)", strings.Repeat(", ?", len(types)-1)), -1)
				queryStr = strings.Replace(query.query, "name = ?", fmt.Sprintf("name IN (?%s)", strings.Repeat(", ?", len(names)-1)), -1)

				sqlStmt, err = prepare(tx, queryStr)
				if err != nil {
					return nil, fmt.Errorf("Failed to prepare stmt: %w", err)
				}
			} else {
				sqlStmt = Stmt(tx, instanceObjectsByTypeAndName)
			}

			args = []any{types, names}
		} else if projects != nil && nodes != nil && ids == nil && names == nil && types == nil {
			if len(filters) > 1 {
				var queryStr string
				query := stmts[instanceObjectsByProjectAndNode]
				queryStr = strings.Replace(query.query, "project = ?", fmt.Sprintf("project IN (?%s)", strings.Repeat(", ?", len(projects)-1)), -1)
				queryStr = strings.Replace(query.query, "node = ?", fmt.Sprintf("node IN (?%s)", strings.Repeat(", ?", len(nodes)-1)), -1)

				sqlStmt, err = prepare(tx, queryStr)
				if err != nil {
					return nil, fmt.Errorf("Failed to prepare stmt: %w", err)
				}
			} else {
				sqlStmt = Stmt(tx, instanceObjectsByProjectAndNode)
			}

			args = []any{projects, nodes}
		} else if projects != nil && names != nil && ids == nil && nodes == nil && types == nil {
			if len(filters) > 1 {
				var queryStr string
				query := stmts[instanceObjectsByProjectAndName]
				queryStr = strings.Replace(query.query, "project = ?", fmt.Sprintf("project IN (?%s)", strings.Repeat(", ?", len(projects)-1)), -1)
				queryStr = strings.Replace(query.query, "name = ?", fmt.Sprintf("name IN (?%s)", strings.Repeat(", ?", len(names)-1)), -1)

				sqlStmt, err = prepare(tx, queryStr)
				if err != nil {
					return nil, fmt.Errorf("Failed to prepare stmt: %w", err)
				}
			} else {
				sqlStmt = Stmt(tx, instanceObjectsByProjectAndName)
			}

			args = []any{projects, names}
		} else if nodes != nil && names != nil && ids == nil && projects == nil && types == nil {
			if len(filters) > 1 {
				var queryStr string
				query := stmts[instanceObjectsByNodeAndName]
				queryStr = strings.Replace(query.query, "node = ?", fmt.Sprintf("node IN (?%s)", strings.Repeat(", ?", len(nodes)-1)), -1)
				queryStr = strings.Replace(query.query, "name = ?", fmt.Sprintf("name IN (?%s)", strings.Repeat(", ?", len(names)-1)), -1)

				sqlStmt, err = prepare(tx, queryStr)
				if err != nil {
					return nil, fmt.Errorf("Failed to prepare stmt: %w", err)
				}
			} else {
				sqlStmt = Stmt(tx, instanceObjectsByNodeAndName)
			}

			args = []any{nodes, names}
		} else if types != nil && ids == nil && projects == nil && names == nil && nodes == nil {
			if len(filters) > 1 {
				var queryStr string
				query := stmts[instanceObjectsByType]
				queryStr = strings.Replace(query.query, "type = ?", fmt.Sprintf("type IN (?%s)", strings.Repeat(", ?", len(types)-1)), -1)

				sqlStmt, err = prepare(tx, queryStr)
				if err != nil {
					return nil, fmt.Errorf("Failed to prepare stmt: %w", err)
				}
			} else {
				sqlStmt = Stmt(tx, instanceObjectsByType)
			}

			args = []any{types}
		} else if projects != nil && ids == nil && names == nil && nodes == nil && types == nil {
			if len(filters) > 1 {
				var queryStr string
				query := stmts[instanceObjectsByProject]
				queryStr = strings.Replace(query.query, "project = ?", fmt.Sprintf("project IN (?%s)", strings.Repeat(", ?", len(projects)-1)), -1)

				sqlStmt, err = prepare(tx, queryStr)
				if err != nil {
					return nil, fmt.Errorf("Failed to prepare stmt: %w", err)
				}
			} else {
				sqlStmt = Stmt(tx, instanceObjectsByProject)
			}

			args = []any{projects}
		} else if nodes != nil && ids == nil && projects == nil && names == nil && types == nil {
			if len(filters) > 1 {
				var queryStr string
				query := stmts[instanceObjectsByNode]
				queryStr = strings.Replace(query.query, "node = ?", fmt.Sprintf("node IN (?%s)", strings.Repeat(", ?", len(nodes)-1)), -1)

				sqlStmt, err = prepare(tx, queryStr)
				if err != nil {
					return nil, fmt.Errorf("Failed to prepare stmt: %w", err)
				}
			} else {
				sqlStmt = Stmt(tx, instanceObjectsByNode)
			}

			args = []any{nodes}
		} else if names != nil && ids == nil && projects == nil && nodes == nil && types == nil {
			if len(filters) > 1 {
				var queryStr string
				query := stmts[instanceObjectsByName]
				queryStr = strings.Replace(query.query, "name = ?", fmt.Sprintf("name IN (?%s)", strings.Repeat(", ?", len(names)-1)), -1)

				sqlStmt, err = prepare(tx, queryStr)
				if err != nil {
					return nil, fmt.Errorf("Failed to prepare stmt: %w", err)
				}
			} else {
				sqlStmt = Stmt(tx, instanceObjectsByName)
			}

			args = []any{names}
		} else if ids != nil && projects == nil && names == nil && nodes == nil && types == nil {
			if len(filters) > 1 {
				var queryStr string
				query := stmts[instanceObjectsByID]
				queryStr = strings.Replace(query.query, "id = ?", fmt.Sprintf("id IN (?%s)", strings.Repeat(", ?", len(ids)-1)), -1)

				sqlStmt, err = prepare(tx, queryStr)
				if err != nil {
					return nil, fmt.Errorf("Failed to prepare stmt: %w", err)
				}
			} else {
				sqlStmt = Stmt(tx, instanceObjectsByID)
			}

			args = []any{ids}
		} else if ids == nil && projects == nil && names == nil && nodes == nil && types == nil {
			sqlStmt = Stmt(tx, instanceObjects)
			args = []any{}
		} else {
			return nil, fmt.Errorf("No statement exists for the given Filter")
		}
	}

	// Dest function for scanning a row.
	dest := func(i int) []any {
		objects = append(objects, Instance{})
		return []any{
			&objects[i].ID,
			&objects[i].Project,
			&objects[i].Name,
			&objects[i].Node,
			&objects[i].Type,
			&objects[i].Architecture,
			&objects[i].Ephemeral,
			&objects[i].CreationDate,
			&objects[i].Stateful,
			&objects[i].LastUseDate,
			&objects[i].Description,
			&objects[i].ExpiryDate,
		}
	}

	// Select.
	allArgs := []any{}
	for _, arg := range args {
		allArgs = append(allArgs, arg.([]any)...)
	}

	err = query.SelectObjects(sqlStmt, dest, allArgs...)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"instances\" table: %w", err)
	}

	return objects, nil
}

// GetInstanceDevices returns all available Instance Devices
// generator: instance GetMany
func GetInstanceDevices(ctx context.Context, tx *sql.Tx, instanceID int) (map[string]Device, error) {
	instanceDevices, err := GetDevices(ctx, tx, "instance")
	if err != nil {
		return nil, err
	}

	devices := map[string]Device{}
	for _, ref := range instanceDevices[instanceID] {
		_, ok := devices[ref.Name]
		if !ok {
			devices[ref.Name] = ref
		} else {
			return nil, fmt.Errorf("Found duplicate Device with name %q", ref.Name)
		}
	}

	return devices, nil
}

// GetInstanceConfig returns all available Instance Config
// generator: instance GetMany
func GetInstanceConfig(ctx context.Context, tx *sql.Tx, instanceID int) (map[string]string, error) {
	instanceConfig, err := GetConfig(ctx, tx, "instance")
	if err != nil {
		return nil, err
	}

	config, ok := instanceConfig[instanceID]
	if !ok {
		config = map[string]string{}
	}

	return config, nil
}

// GetInstance returns the instance with the given key.
// generator: instance GetOne
func GetInstance(ctx context.Context, tx *sql.Tx, project string, name string) (*Instance, error) {
	filter := InstanceFilter{}
	filter.Project = &project
	filter.Name = &name

	objects, err := GetInstances(ctx, tx, filter)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"instances\" table: %w", err)
	}

	switch len(objects) {
	case 0:
		return nil, api.StatusErrorf(http.StatusNotFound, "Instance not found")
	case 1:
		return &objects[0], nil
	default:
		return nil, fmt.Errorf("More than one \"instances\" entry matches")
	}
}

// GetInstanceID return the ID of the instance with the given key.
// generator: instance ID
func GetInstanceID(ctx context.Context, tx *sql.Tx, project string, name string) (int64, error) {
	stmt := Stmt(tx, instanceID)
	rows, err := stmt.Query(project, name)
	if err != nil {
		return -1, fmt.Errorf("Failed to get \"instances\" ID: %w", err)
	}

	defer func() { _ = rows.Close() }()

	// Ensure we read one and only one row.
	if !rows.Next() {
		return -1, api.StatusErrorf(http.StatusNotFound, "Instance not found")
	}

	var id int64
	err = rows.Scan(&id)
	if err != nil {
		return -1, fmt.Errorf("Failed to scan ID: %w", err)
	}

	if rows.Next() {
		return -1, fmt.Errorf("More than one row returned")
	}

	err = rows.Err()
	if err != nil {
		return -1, fmt.Errorf("Result set failure: %w", err)
	}

	return id, nil
}

// InstanceExists checks if a instance with the given key exists.
// generator: instance Exists
func InstanceExists(ctx context.Context, tx *sql.Tx, project string, name string) (bool, error) {
	_, err := GetInstanceID(ctx, tx, project, name)
	if err != nil {
		if api.StatusErrorCheck(err, http.StatusNotFound) {
			return false, nil
		}

		return false, err
	}

	return true, nil
}

// CreateInstance adds a new instance to the database.
// generator: instance Create
func CreateInstance(ctx context.Context, tx *sql.Tx, object Instance) (int64, error) {
	// Check if a instance with the same key exists.
	exists, err := InstanceExists(ctx, tx, object.Project, object.Name)
	if err != nil {
		return -1, fmt.Errorf("Failed to check for duplicates: %w", err)
	}

	if exists {
		return -1, api.StatusErrorf(http.StatusConflict, "This \"instances\" entry already exists")
	}

	args := make([]any, 11)

	// Populate the statement arguments.
	args[0] = object.Project
	args[1] = object.Name
	args[2] = object.Node
	args[3] = object.Type
	args[4] = object.Architecture
	args[5] = object.Ephemeral
	args[6] = object.CreationDate
	args[7] = object.Stateful
	args[8] = object.LastUseDate
	args[9] = object.Description
	args[10] = object.ExpiryDate

	// Prepared statement to use.
	stmt := Stmt(tx, instanceCreate)

	// Execute the statement.
	result, err := stmt.Exec(args...)
	if err != nil {
		return -1, fmt.Errorf("Failed to create \"instances\" entry: %w", err)
	}

	id, err := result.LastInsertId()
	if err != nil {
		return -1, fmt.Errorf("Failed to fetch \"instances\" entry ID: %w", err)
	}

	return id, nil
}

// CreateInstanceDevices adds new instance Devices to the database.
// generator: instance Create
func CreateInstanceDevices(ctx context.Context, tx *sql.Tx, instanceID int64, devices map[string]Device) error {
	for key, device := range devices {
		device.ReferenceID = int(instanceID)
		devices[key] = device
	}

	err := CreateDevices(ctx, tx, "instance", devices)
	if err != nil {
		return fmt.Errorf("Insert Device failed for Instance: %w", err)
	}

	return nil
}

// CreateInstanceConfig adds new instance Config to the database.
// generator: instance Create
func CreateInstanceConfig(ctx context.Context, tx *sql.Tx, instanceID int64, config map[string]string) error {
	referenceID := int(instanceID)
	for key, value := range config {
		insert := Config{
			ReferenceID: referenceID,
			Key:         key,
			Value:       value,
		}

		err := CreateConfig(ctx, tx, "instance", insert)
		if err != nil {
			return fmt.Errorf("Insert Config failed for Instance: %w", err)
		}

	}

	return nil
}

// RenameInstance renames the instance matching the given key parameters.
// generator: instance Rename
func RenameInstance(ctx context.Context, tx *sql.Tx, project string, name string, to string) error {
	stmt := Stmt(tx, instanceRename)
	result, err := stmt.Exec(to, project, name)
	if err != nil {
		return fmt.Errorf("Rename Instance failed: %w", err)
	}

	n, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("Fetch affected rows failed: %w", err)
	}

	if n != 1 {
		return fmt.Errorf("Query affected %d rows instead of 1", n)
	}

	return nil
}

// DeleteInstance deletes the instance matching the given key parameters.
// generator: instance DeleteOne-by-Project-and-Name
func DeleteInstance(ctx context.Context, tx *sql.Tx, project string, name string) error {
	stmt := Stmt(tx, instanceDeleteByProjectAndName)
	result, err := stmt.Exec(project, name)
	if err != nil {
		return fmt.Errorf("Delete \"instances\": %w", err)
	}

	n, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("Fetch affected rows: %w", err)
	}

	if n == 0 {
		return api.StatusErrorf(http.StatusNotFound, "Instance not found")
	} else if n > 1 {
		return fmt.Errorf("Query deleted %d Instance rows instead of 1", n)
	}

	return nil
}

// UpdateInstance updates the instance matching the given key parameters.
// generator: instance Update
func UpdateInstance(ctx context.Context, tx *sql.Tx, project string, name string, object Instance) error {
	id, err := GetInstanceID(ctx, tx, project, name)
	if err != nil {
		return err
	}

	stmt := Stmt(tx, instanceUpdate)
	result, err := stmt.Exec(object.Project, object.Name, object.Node, object.Type, object.Architecture, object.Ephemeral, object.CreationDate, object.Stateful, object.LastUseDate, object.Description, object.ExpiryDate, id)
	if err != nil {
		return fmt.Errorf("Update \"instances\" entry failed: %w", err)
	}

	n, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("Fetch affected rows: %w", err)
	}

	if n != 1 {
		return fmt.Errorf("Query updated %d rows instead of 1", n)
	}

	return nil
}

// UpdateInstanceDevices updates the instance Device matching the given key parameters.
// generator: instance Update
func UpdateInstanceDevices(ctx context.Context, tx *sql.Tx, instanceID int64, devices map[string]Device) error {
	err := UpdateDevices(ctx, tx, "instance", int(instanceID), devices)
	if err != nil {
		return fmt.Errorf("Replace Device for Instance failed: %w", err)
	}

	return nil
}

// UpdateInstanceConfig updates the instance Config matching the given key parameters.
// generator: instance Update
func UpdateInstanceConfig(ctx context.Context, tx *sql.Tx, instanceID int64, config map[string]string) error {
	err := UpdateConfig(ctx, tx, "instance", int(instanceID), config)
	if err != nil {
		return fmt.Errorf("Replace Config for Instance failed: %w", err)
	}

	return nil
}
